# Generated by Django 3.2 on 2021-05-19 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserLogin', '0004_auto_20210518_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='level_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RolePermisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol2_assign', to='UserLogin.roles')),
                ('selected_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
